// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// start_profiler
void start_profiler(String str);
RcppExport SEXP _rgprofiler_start_profiler(SEXP strSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type str(strSEXP);
    start_profiler(str);
    return R_NilValue;
END_RCPP
}
// stop_profiler
void stop_profiler();
RcppExport SEXP _rgprofiler_stop_profiler() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    stop_profiler();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rgprofiler_start_profiler", (DL_FUNC) &_rgprofiler_start_profiler, 1},
    {"_rgprofiler_stop_profiler", (DL_FUNC) &_rgprofiler_stop_profiler, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_rgprofiler(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
